import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/frametwo">FrameTwo</Link>
        </li>
        <li>
          <Link to="/frameone">FrameOne</Link>
        </li>
        <li>
          <Link to="/frameeleven">FrameEleven</Link>
        </li>
        <li>
          <Link to="/frameseventeen">FrameSeventeen</Link>
        </li>
        <li>
          <Link to="/frame100">Frame100</Link>
        </li>
        <li>
          <Link to="/frame106">Frame106</Link>
        </li>
        <li>
          <Link to="/framenine">FrameNine</Link>
        </li>
        <li>
          <Link to="/framethirteen">FrameThirteen</Link>
        </li>
        <li>
          <Link to="/frameninetyseven">FrameNinetySeven</Link>
        </li>
        <li>
          <Link to="/frame101">Frame101</Link>
        </li>
        <li>
          <Link to="/frame104">Frame104</Link>
        </li>
        <li>
          <Link to="/framefifteen">FrameFifteen</Link>
        </li>
        <li>
          <Link to="/frameninetyeight">FrameNinetyEight</Link>
        </li>
        <li>
          <Link to="/frame102">Frame102</Link>
        </li>
        <li>
          <Link to="/framesixteen">FrameSixteen</Link>
        </li>
        <li>
          <Link to="/frame103">Frame103</Link>
        </li>
        <li>
          <Link to="/framefourteen">FrameFourteen</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
